platform :ios, '13.0'

target 'Flash Chat iOS13' do


  # Pods for Flash Chat iOS13
pod 'CLTypingLabel', '0.4.0'
pod 'Firebase', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'FirebaseAuth', :modular_headers => true
pod 'FirebaseFirestore', :modular_headers => true
pod 'GoogleUtilities/Environment', :modular_headers => true

end
